shadowsocks:
  image: kycfeel/shadowsocks-server:latest
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "443:443"
  volumes:
    - ./shadowsocks-conf:/etc/shadowsocks-conf
    - ./shadowsocks-certs:/etc/shadowsocks-certs
  entrypoint: >
    /bin/sh -c "
    ss-server -c /etc/shadowsocks-conf/config.json
    "